---
- name: Install nginx
  ansible.builtin.apt:
    update_cache: True
    name: nginx
    state: latest

- name: Copy nginx configs
  template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/site-{{ item }}.conf'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
  notify: restart nginx

- name: Create site folders
  file:
    path: '/var/www/{{ item }}'
    state: directory
  loop: '{{ sites }}'

- name: Copy index from templates
  template:
    src: 'index.html.j2'
    dest: '/var/www/{{ item }}/index.html'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
